language: go

go:
  - tip

services:
  - mysql
  - postgres
  - sqlite3

before_script:
  - mysql -e "CREATE DATABASE gorptest;"
  - mysql -u root -e "GRANT ALL ON gorptest.* TO gorptest@localhost IDENTIFIED BY 'gorptest'"
  - psql -c "CREATE USER gorptest PASSWORD 'gorptest';" -U postgres
  - psql -c "CREATE DATABASE gorptest OWNER gorptest;" -U postgres
  - go list -f '{{range .TestImports}}{{.}}{{end}}' . | xargs go get
